<?php

/**
 * @file
 * Module file for the Workbench Moderation Extras module.
 */

module_load_include('inc', 'workbench_moderation_extras');

/**
 * Implements hook_menu().
 */
function workbench_moderation_extras_menu() {
  $items = array();

  // Module settings
  $items["admin/config/workbench/moderation_extras"] = array(
    'title' => 'Workbench Moderation Extras',
    'description' => 'Allows to set users to receive email notifications for certain transition states',
    'page callback' => 'drupal_get_form',
    'page arguments' => array(
      'workbench_moderation_extras_admin_settings',
    ),
    'access arguments' => array(
      'administer workbench moderation',
    ),
    'file' => 'workbench_moderation_extras.admin.inc',
  );

  return $items;
}

// let's try hook_cron to change states...

/**
 * Implements hook_cron().
 */
function workbench_moderation_extras_cron() {
  // get all published nodes that have been updated more then needed seconds ago
  $nids = _workbench_moderation_extras_get_published_state_nodes();

  // Change their state
  // So, a state is tied by a vid (revision id)
  // That means we need a new revision copy?
  if (!empty($nids)) {

    foreach ($nids as $nid) {
      _workbench_moderation_extras_change_state($nid);
    }

    // Notify all needed users about it
    $users = _workbench_moderation_extras_get_users();

    foreach($users as $user) {
      _workbench_moderation_extras_mail($user);
      // that moment when you make an infinite recursive loop and you wonder why... Because of hooks :)
    }
  }
}

/**
 * Implements hook_mail().
 */
function workbench_moderation_extras_mail($key, &$message, $params) {
  if ($key === 'regular_review') {
    $message['subject'] = 'Some nodes were set to Regular Review';
    $message['body'] = array($params);
  }
}
